In [1]:
#import the necessary Libraries
import numpy as np
import pandas as pd
import seaborn as sns
import warnings
# Ignore all warnings
warnings.filterwarnings("ignore")

In [2]:
#Load the dataset
data=pd.read_csv('50_Startups.csv')

In [3]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
data.shape

(50, 5)

In [5]:
data.dtypes

R&D Spend          float64
Administration     float64
Marketing Spend    float64
State               object
Profit             float64
dtype: object

In [6]:
data.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [7]:
data['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [8]:
data['State'].value_counts()

State
New York      17
California    17
Florida       16
Name: count, dtype: int64

In [9]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [10]:
#Encoding=Converting Categorical Column to Numerical Column
from sklearn.preprocessing import LabelEncoder

In [11]:
#initialise the LabelEncode
le=LabelEncoder()

In [12]:
data['State']=le.fit_transform(data['State'])

In [13]:
data.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     int32  
 4   Profit           50 non-null     float64
dtypes: float64(4), int32(1)
memory usage: 1.9 KB


In [15]:
#Sepearate the dependent and Independent variable
y=data['Profit']
x=data.drop(columns=['Profit'],axis=1)

In [18]:
x.head()

R&D Spend  Administration  Marketing Spend  State
0  165349.20       136897.80        471784.10      2
1  162597.70       151377.59        443898.53      0
2  153441.51       101145.55        407934.54      1
3  144372.41       118671.85        383199.62      2
4  142107.34        91391.77        366168.42      1

In [24]:
y

0     192261.83
1     191792.06
2     191050.39
3     182901.99
4     166187.94
5     156991.12
6     156122.51
7     155752.60
8     152211.77
9     149759.96
10    146121.95
11    144259.40
12    141585.52
13    134307.35
14    132602.65
15    129917.04
16    126992.93
17    125370.37
18    124266.90
19    122776.86
20    118474.03
21    111313.02
22    110352.25
23    108733.99
24    108552.04
25    107404.34
26    105733.54
27    105008.31
28    103282.38
29    101004.64
30     99937.59
31     97483.56
32     97427.84
33     96778.92
34     96712.80
35     96479.51
36     90708.19
37     89949.14
38     81229.06
39     81005.76
40     78239.91
41     77798.83
42     71498.49
43     69758.98
44     65200.33
45     64926.08
46     49490.75
47     42559.73
48     35673.41
49     14681.40
Name: Profit, dtype: float64

In [20]:
#Scaling on Independent Feratures
from sklearn.preprocessing import StandardScaler

In [22]:
names=x.columns

In [23]:
names

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State'], dtype='object')

In [25]:
scale=StandardScaler()

In [26]:
x=scale.fit_transform(x)

In [27]:
x

array([[ 2.01641149e+00,  5.60752915e-01,  2.15394309e+00,
         1.21267813e+00],
       [ 1.95586034e+00,  1.08280658e+00,  1.92360040e+00,
        -1.21267813e+00],
       [ 1.75436374e+00, -7.28257028e-01,  1.62652767e+00,
         0.00000000e+00],
       [ 1.55478369e+00, -9.63646307e-02,  1.42221024e+00,
         1.21267813e+00],
       [ 1.50493720e+00, -1.07991935e+00,  1.28152771e+00,
         0.00000000e+00],
       [ 1.27980001e+00, -7.76239071e-01,  1.25421046e+00,
         1.21267813e+00],
       [ 1.34006641e+00,  9.32147208e-01, -6.88149930e-01,
        -1.21267813e+00],
       [ 1.24505666e+00,  8.71980011e-01,  9.32185978e-01,
         0.00000000e+00],
       [ 1.03036886e+00,  9.86952101e-01,  8.30886909e-01,
         1.21267813e+00],
       [ 1.09181921e+00, -4.56640246e-01,  7.76107440e-01,
        -1.21267813e+00],
       [ 6.20398248e-01, -3.87599089e-01,  1.49807267e-01,
         0.00000000e+00],
       [ 5.93085418e-01, -1.06553960e+00,  3.19833623e-01,
      

In [28]:
x=pd.DataFrame(x,columns=names)
x

R&D Spend  Administration  Marketing Spend     State
0    2.016411        0.560753         2.153943  1.212678
1    1.955860        1.082807         1.923600 -1.212678
2    1.754364       -0.728257         1.626528  0.000000
3    1.554784       -0.096365         1.422210  1.212678
4    1.504937       -1.079919         1.281528  0.000000
5    1.279800       -0.776239         1.254210  1.212678
6    1.340066        0.932147        -0.688150 -1.212678
7    1.245057        0.871980         0.932186  0.000000
8    1.030369        0.986952         0.830887  1.212678
9    1.091819       -0.456640         0.776107 -1.212678
10   0.620398       -0.387599         0.149807  0.000000
11   0.593085       -1.065540         0.319834 -1.212678
12   0.443260        0.215449         0.320617  0.000000
13   0.402078        0.510179         0.343957 -1.212678
14   1.017181        1.269199         0.375742  0.000000
15   0.897913        0.045868         0.419219  1.212678
16   0.094441        0.009118         0.440446 -1.212678
17   0.460720        0.855666         0.591017  1.212678
18   0.396725       -0.258465         0.692992  0.000000
19   0.279442        1.159837        -1.743127  1.212678
20   0.055726       -0.269588         0.723926 -1.212678
21   0.102724        1.169186         0.732788  1.212678
22   0.006007        0.051850         0.762376  0.000000
23  -0.136201       -0.562211         0.774349  0.000000
24   0.073115       -0.795469        -0.581939  1.212678
25  -0.199312        0.656489        -0.603517 -1.212678
26   0.035370        0.821718        -0.635835  0.000000
27  -0.035519        0.235069         1.174271  1.212678
28  -0.168793        2.210141        -0.767189  0.000000
29  -0.178609        1.142457        -0.858134  1.212678
30  -0.258074       -0.205629        -0.990357  0.000000
31  -0.276958        1.130554        -1.014419  1.212678
32  -0.226949        0.283924        -1.362450 -1.212678
33  -0.401129       -0.659324         0.029817  0.000000
34  -0.600682        1.310535        -0.001879 -1.212678
35  -0.609750       -1.308658        -0.045493  1.212678
36  -0.991570        0.205925        -0.081763  0.000000
37  -0.652532       -2.525994        -0.115608 -1.212678
38  -1.177178       -1.997270        -0.212785  1.212678
39  -0.773820       -1.383122        -0.297583 -1.212678
40  -0.989577       -0.100900        -0.315786 -1.212678
41  -1.008534       -1.320796        -0.384552  0.000000
42  -1.102106       -0.906938        -0.520596 -1.212678
43  -1.281134        0.217682        -1.449605  1.212678
44  -1.134305        1.206419        -1.509074 -1.212678
45  -1.600350        0.101254        -1.727400  1.212678
46  -1.593413       -0.199322         0.711122  0.000000
47  -1.622362        0.507722        -1.743127 -1.212678
48  -1.610433       -2.509409        -1.743127  1.212678
49  -1.622362       -0.157226        -1.369985 -1.212678

In [45]:
from sklearn.model_selection import train_test_split

In [63]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
#Splitting Dataset in 80% traing dataset and 20% in Test Dataset

In [64]:
#model building
from sklearn.linear_model import LinearRegression

In [65]:
model=LinearRegression()

In [66]:
model

LinearRegression()

In [67]:
#Fit the model with train data
model.fit(x_train,y_train)

LinearRegression()

In [68]:
# test the Model
pred=model.predict(x_test)

In [69]:
pred

array([103959.40508021, 132398.73236694, 133529.03790148,  72958.28368314,
       179534.78737166, 115533.62584099,  67476.95847883,  98504.36199396,
       114789.16083781, 168972.21909945])

In [70]:
y_test

28    103282.38
11    144259.40
10    146121.95
41     77798.83
2     191050.39
27    105008.31
38     81229.06
31     97483.56
22    110352.25
4     166187.94
Name: Profit, dtype: float64

In [71]:
E=pred-y_test

In [72]:
E

28      677.025080
11   -11860.667633
10   -12592.912099
41    -4840.546317
2    -11515.602628
27    10525.315841
38   -13752.101521
31     1020.801994
22     4436.910838
4      2784.279099
Name: Profit, dtype: float64

In [73]:
#r2 Score--Accuracy of the model


In [74]:
from sklearn.metrics import r2_score

In [75]:
r2_score(pred,y_test)*100

93.46674198705868

In [76]:
model.coef_

array([35316.84726493,   838.83297133,  4227.89488204,   260.47901392])

In [77]:
model.intercept_

111310.28925308927